// Mapa de compatibilidad: conserva las claves historicas que estaban embebidas en base64,
// pero ahora apunta a archivos PNG sueltos para reducir el peso del JavaScript.
window.mockImagesB64 = {
    "NovelaGrafica_Prof Murcia.png": "assets/novela_grafica_prof_murcia.jpg",
    "novela_grafica_prof_murcia.png": "assets/novela_grafica_prof_murcia.jpg",
    "novela_grafica_prof_murcia.jpg": "assets/novela_grafica_prof_murcia.jpg",
    "Portada_Dilema del color.png": "assets/portada_dilema_del_color.jpg",
    "portada_dilema_del_color.png": "assets/portada_dilema_del_color.jpg",
    "portada_dilema_del_color.jpg": "assets/portada_dilema_del_color.jpg",
    "NovelaGrafica_Prof Chat2.png": "assets/novela_grafica_prof_chat2.jpg",
    "novela_grafica_prof_chat2.png": "assets/novela_grafica_prof_chat2.jpg",
    "novela_grafica_prof_chat2.jpg": "assets/novela_grafica_prof_chat2.jpg",
    "NovelaGrafica_Paz.png": "assets/novela_grafica_paz.jpg",
    "novela_grafica_paz.png": "assets/novela_grafica_paz.jpg",
    "novela_grafica_paz.jpg": "assets/novela_grafica_paz.jpg",
    "inicio.jpg": "assets/inicio.jpg",
    "inicio.png": "assets/inicio.jpg",
    "NovelaGrafica_Xochi.png": "assets/novela_grafica_xochi.jpg",
    "novela_grafica_xochi.png": "assets/novela_grafica_xochi.jpg",
    "novela_grafica_xochi.jpg": "assets/novela_grafica_xochi.jpg",
    "La_escuela.png": "assets/la_escuela.jpg",
    "la_escuela.png": "assets/la_escuela.jpg",
    "la_escuela.jpg": "assets/la_escuela.jpg",
    "NovelaGrafica_Don Tico2.png": "assets/novela_grafica_don_tico2.jpg",
    "novela_grafica_don_tico2.png": "assets/novela_grafica_don_tico2.jpg",
    "novela_grafica_don_tico2.jpg": "assets/novela_grafica_don_tico2.jpg",
    "NovelaGrafica_Pete.png": "assets/novela_grafica_pete.jpg",
    "novela_grafica_pete.png": "assets/novela_grafica_pete.jpg",
    "novela_grafica_pete.jpg": "assets/novela_grafica_pete.jpg",
    "NovelaGrafica_Prof Maximiliano.png": "assets/novela_grafica_prof_maximiliano.jpg",
    "novela_grafica_prof_maximiliano.png": "assets/novela_grafica_prof_maximiliano.jpg",
    "novela_grafica_prof_maximiliano.jpg": "assets/novela_grafica_prof_maximiliano.jpg",
    "NovelaGrafica_Dani.png": "assets/novela_grafica_dani.jpg",
    "novela_grafica_dani.png": "assets/novela_grafica_dani.jpg",
    "novela_grafica_dani.jpg": "assets/novela_grafica_dani.jpg"
};
